### ISSUE TITLE
 A twitter-wjs node is already present

### ISSUE THREAD

**Issue by jhliberty** [aethermx/ember-cli-twitter-feed#1]
Loading a page with the twitter-feed already embedded loads but gives the following errors in the console:

 A twitter-wjs node is already present - twitter-feed.js:31
Uncaught error: Assertion Failed: A twitter-wsj node was inserted. ember.debug.js:5191

![screen shot 2015-09-20 at 12 38 37 am](https://cloud.githubusercontent.com/assets/449321/9979396/08cf9ea4-5f30-11e5-9ffa-0ee604851e17.png)

**Comment by givanse** [comment]
What Ember version were you using?

Its not clear to me what are the steps to reproduce this. Can you elaborate a bit more?

**Comment by jhliberty** [comment]
I'm using v2.0.2. I have a sidebar component that renders a twitter-feed component which is literally:

```
{{#twitter-feed}}
    <a class="twitter-timeline" data-dnt="true" href="https://twitter.com/JHLiberty" data-widget-id="645412270902673408">Tweets by @JHLiberty</a>
   <twitters script here>
{{/twitter-feed}}
```

Just loading a page with this component loaded on it causes the error.

**Comment by givanse** [comment]
Ok, its probably an Ember 2 problem. Just remember that you dont need to add the JS line.

**Comment by jhliberty** [comment]
I took out the JS line and this seems to have fixed this issue - awesome!
