### ISSUE TITLE
Lots of CSP issues

### ISSUE THREAD

**Issue by jhliberty** [aethermx/ember-cli-twitter-feed#3]
Had to manually add the following to environments.js's contentSecurityPolicy to stop console errors:

script-src: http://platform.twitter.com https://cdn.syndication.twimg.com
img-src: https://pbs.twimg.com https://abs.twimg.com https://syndication.twitter.com http://platform.twitter.com data:;
style-src: http://platform.twitter.com

**Comment by givanse** [comment]
Sorry, I forgot to mention in the README that you can copy the CSPs from: https://github.com/aethermx/ember-cli-twitter-feed/blob/master/tests/dummy/config/environment.js#L46

Ideally the CSPs would be merged from an addon to the host app. For now, this is just a wish
https://github.com/rwjblue/ember-cli-content-security-policy/pull/20#issuecomment-118175209
